from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from teacher import request_views
urlpatterns = [
    path('home/',request_views.displayhome),
    path('Teacher/',request_views.Teacher_display),
    path('Award_fellowship/',request_views.Award_fellowship_display),
    path('Revenue_consultancy_corporate_training/',request_views.Revenue_consultancy_corporate_training_display),
    path('Funds_provided_to_teacher/',request_views.Funds_provided_to_teacher_display),
    path('Book_research_published/',request_views.Book_research_published_display),
    path('E_content_devp/',request_views.E_content_devp_display),
    path('Faculty_dev_program/',request_views.Faculty_dev_program_display),
    path('Teacher_collaborative_activity_participation/',request_views.Teacher_collaborative_activity_participation_display),
    path('teacher_tables/', request_views.teacher_tables),
    path('Teacher_delete/<id>/', request_views.Teacher_delete,name='Teacher_delete'),
    path('Award_fellowship_delete/<id>/', request_views.Award_fellowship_delete,name='Award_fellowship_delete'),
    path('Revenue_consultancy_corporate_training_delete/<id>/', request_views.Revenue_consultancy_corporate_training_delete,name='Revenue_consultancy_corporate_training_delete'),
    path('Funds_provided_to_teacher_delete/<id>/', request_views.Funds_provided_to_teacher_delete,name='Funds_provided_to_teacher_delete'),
    path('Book_research_published_delete/<id>/', request_views.Book_research_published_delete,name='Book_research_published_delete'),
    path('E_content_devp_delete/<id>/', request_views.E_content_devp_delete,name='E_content_devp_delete'),
    path('Faculty_dev_program_delete/<id>/', request_views.Faculty_dev_program_delete,name='Faculty_dev_program_delete'),
    path('Teacher_collaborative_activity_participation_delete/<id>/', request_views.Teacher_collaborative_activity_participation_delete,name='Teacher_collaborative_activity_participation_delete'),
    path('Teacher_add/', request_views.Teacher_add,name='Teacher_add'),
    path('Award_fellowship_add/', request_views.Award_fellowship_add, name='Award_fellowship_add'),
    path('Revenue_consultancy_corporate_training_add/', request_views.Revenue_consultancy_corporate_training_add, name='Revenue_consultancy_corporate_training_add'),
    path('Funds_provided_to_teacher_add/', request_views.Funds_provided_to_teacher_add, name='Funds_provided_to_teacher_add'),
    path('Book_research_published_add/', request_views.Book_research_published_add, name='Book_research_published_add'),
    path('E_content_devp_add/', request_views.E_content_devp_add, name='E_content_devp_add'),
    path('Faculty_dev_program_add/', request_views.Faculty_dev_program_add, name='Faculty_dev_program_add'),
    path('Teacher_collaborative_activity_participation_add/', request_views.Teacher_collaborative_activity_participation_add, name='Teacher_collaborative_activity_participation_add'),
    path('Award_fellowship_add_display/', request_views.Award_fellowship_add_display, name='Award_fellowship_add_display'),
    path('Revenue_consultancy_corporate_training_add_display/', request_views.Revenue_consultancy_corporate_training_add_display,name='Revenue_consultancy_corporate_training_add_display'),
    path('Funds_provided_to_teacher_add_display/', request_views.Funds_provided_to_teacher_add_display,name='Funds_provided_to_teacher_add_display'),
    path('Book_research_published_add_display/', request_views.Book_research_published_add_display, name='Book_research_published_add_display'),
    path('E_content_devp_add_display/', request_views.E_content_devp_add_display, name='E_content_devp_add_display'),
    path('Faculty_dev_program_add_display/', request_views.Faculty_dev_program_add_display, name='Faculty_dev_program_add_display'),
    path('Teacher_collaborative_activity_participation_add_display/',request_views.Teacher_collaborative_activity_participation_add_display,name='Teacher_collaborative_activity_participation_add_display'),
    path('Teacher_edit_display/<id>/', request_views.Teacher_edit_display, name='Teacher_edit_display'),
    path('Award_fellowship_edit_display/<id>/', request_views.Award_fellowship_edit_display,name='Award_fellowship_edit_display'),
    path('Revenue_consultancy_corporate_training_edit_display/<id>/', request_views.Revenue_consultancy_corporate_training_edit_display,name='Revenue_consultancy_corporate_training_edit_display'),
    path('Funds_provided_to_teacher_edit_display/<id>/', request_views.Funds_provided_to_teacher_edit_display,name='Funds_provided_to_teacher_edit_display'),
    path('Book_research_published_edit_display/<id>/', request_views.Book_research_published_edit_display, name='Book_research_published_edit_display'),
    path('E_content_devp_edit_display/<id>/', request_views.E_content_devp_edit_display,name='E_content_devp_edit_display'),
    path('Faculty_dev_program_edit_display/<id>/', request_views.Faculty_dev_program_edit_display, name='Faculty_dev_program_edit_display'),
    path('Teacher_collaborative_activity_participation_edit_display/<id>/', request_views.Teacher_collaborative_activity_participation_edit_display,name='Teacher_collaborative_activity_participation_edit_display'),
    path('Teacher_edit/<id>/', request_views.Teacher_edit, name='Teacher_edit'),
    path('Award_fellowship_edit/<id>/', request_views.Award_fellowship_edit, name='Award_fellowship_edit'),
    path('Revenue_consultancy_corporate_training_edit/<id>/', request_views.Revenue_consultancy_corporate_training_edit, name='Revenue_consultancy_corporate_training_edit'),
    path('Funds_provided_to_teacher_edit/<id>/', request_views.Funds_provided_to_teacher_edit,name='Funds_provided_to_teacher_edit'),
    path('Book_research_published_edit/<id>/', request_views.Book_research_published_edit, name='Book_research_published_edit'),
    path('E_content_devp_edit/<id>/', request_views.E_content_devp_edit, name='E_content_devp_edit'),
    path('Faculty_dev_program_edit/<id>/', request_views.Faculty_dev_program_edit, name='Faculty_dev_program_edit'),
    path('Teacher_collaborative_activity_participation_edit/<id>/', request_views.Teacher_collaborative_activity_participation_edit, name='Teacher_collaborative_activity_participation_edit'),
    path('Teacher_add_display/',request_views.Teacher_add_display, name='Teacher_add_display'),
    path('Teacher_bulk_upload/',request_views.Teacher_bulk_upload, name='Teacher_bulk_upload')
]