# Generated by Django 3.2.5 on 2022-11-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginandregister', '0001_initial'),
        ('institute', '0002_collaborative_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loginandregister.alluser')),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('designation', models.CharField(blank=True, max_length=20, null=True)),
                ('appointment_year', models.IntegerField(blank=True, null=True)),
                ('resignation_year', models.IntegerField(blank=True, null=True)),
                ('nature_of_appointment', models.CharField(blank=True, max_length=20)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('present_status', models.CharField(blank=True, max_length=20, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=100, null=True)),
                ('prog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.program')),
            ],
        ),
    ]
