# Generated by Django 3.2.5 on 2022-11-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_collaborative_activity'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_collaborative_activity_participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.collaborative_activity')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue_consultancy_corporate_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('consulting_sponsoring_agency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_details', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('revenue_generated', models.IntegerField(blank=True, null=True)),
                ('number_of_trainee', models.IntegerField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Funds_provided_to_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('name_of_cons_or_research_or_conf', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_spend', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('policy_doc_link', models.CharField(blank=True, max_length=300, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_dev_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='E_content_devp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=50, null=True)),
                ('platform_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_launch', models.DateField(blank=True, null=True)),
                ('doc_link', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('playlist_link', models.CharField(blank=True, max_length=300, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Book_research_published',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_chapter_title', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('publisher_journal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_publish', models.CharField(blank=True, max_length=20, null=True)),
                ('publish_title', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn_issn_number', models.CharField(blank=True, max_length=50, null=True)),
                ('institution_name_during_publication', models.CharField(blank=True, max_length=100, null=True)),
                ('listed_in_ugc_status', models.CharField(blank=True, max_length=10, null=True)),
                ('journal_website_link', models.CharField(blank=True, max_length=300, null=True)),
                ('doc_link', models.CharField(blank=True, max_length=300, null=True)),
                ('is_listed_in_ugc_care_scopus', models.CharField(blank=True, max_length=10, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Award_fellowship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_fellowship_name', models.CharField(blank=True, max_length=50, null=True)),
                ('award_year', models.IntegerField(blank=True, null=True)),
                ('awarding_agency', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
