# Generated by Django 3.2.5 on 2022-11-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_award_fellowship_book_research_published_e_content_devp_faculty_dev_program_funds_provided_to_teache'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_research_published',
            name='author_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
