from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from student import request_views

urlpatterns = [
    path('home/', request_views.displayhomestudent),
    path('academicinfo/', request_views.displayacademicinfo),
    path('Student/',request_views.Student_display),
    path('Scholarship/',request_views.Scholarship_display),
    path('Placement_internship_project/',request_views.Placement_internship_project_display),
    path('Competative_exam/',request_views.Competative_exam_display),
    path('Sports_cultural_award/',request_views.Sports_cultural_award_display),
    path('Student_collaborative_activity_participation/',request_views.Student_collaborative_activity_participation_display),
    path('student_tables/',request_views.student_tables),
    path('Student_delete/<id>/',request_views.Student_delete, name='Student_delete'),
    path('Scholarship_delete/<id>',request_views.Scholarship_delete, name='Scholarship_delete'),
    path('Placement_internship_project_delete/<id>/',request_views.Placement_internship_project_delete, name='Placement_internship_project_delete'),
    path('Competative_exam_delete/<id>/',request_views.Competative_exam_delete,name='Competative_exam_delete'),
    path('Sports_cultural_award_delete/<id>/',request_views.Sports_cultural_award_delete,name='Sports_cultural_award_delete'),
    path('Student_collaborative_activity_participation_delete/<id>/',request_views.Student_collaborative_activity_participation_delete,name='Student_collaborative_activity_participation_delete'),
    path('Student_add/',request_views.Student_add,name='Student_add'),
    path('Scholarship_add/',request_views.Scholarship_add,name='Scholarship_add'),
    path('Placement_internship_project_add/',request_views.Placement_internship_project_add,name='Placement_internship_project_add'),
    path('Competative_exam_add/',request_views.Competative_exam_add,name='Competative_exam_add'),
    path('Sports_cultural_award_add/', request_views.Sports_cultural_award_add, name='Sports_cultural_award_add'),
    path('Student_collaborative_activity_participation_add/', request_views.Student_collaborative_activity_participation_add, name='Student_collaborative_activity_participation_add'),
    path('Scholarship_add_display/',request_views.Scholarship_add_display,name='Scholarship_add_display'),
    path('Placement_internship_project_add_display/', request_views.Placement_internship_project_add_display,name='Placement_internship_project_add_display'),
    path('Competative_exam_add_display/', request_views.Competative_exam_add_display, name='Competative_exam_add_display'),
    path('Sports_cultural_award_add_display/', request_views.Sports_cultural_award_add_display, name='Sports_cultural_award_add_display'),
    path('Student_collaborative_activity_participation_add_display/',request_views.Student_collaborative_activity_participation_add_display,name='Student_collaborative_activity_participation_add_display'),
    path('Student_edit_display/<id>/', request_views.Student_edit_display, name='Student_edit_display'),
    path('Scholarship_edit_display/<id>/',request_views.Scholarship_edit_display,name='Scholarship_edit_display'),
    path('Placement_internship_project_edit_display/<id>/',request_views.Placement_internship_project_edit_display,name='Placement_internship_project_edit_display'),
    path('Competative_exam_edit_display/<id>/',request_views.Competative_exam_edit_display,name='Competative_exam_edit_display'),
    path('Sports_cultural_award_edit_display/<id>/',request_views.Sports_cultural_award_edit_display,name='Sports_cultural_award_edit_display'),
    path('Student_collaborative_activity_participation_edit_display/<id>/', request_views.Student_collaborative_activity_participation_edit_display, name='Student_collaborative_activity_participation_edit_display'),
    path('Student_edit/<id>/',request_views.Student_edit, name='Student_edit'),
    path('Scholarship_edit/<id>/', request_views.Scholarship_edit, name='Scholarship_edit'),
    path('Placement_internship_project_edit/<id>/', request_views.Placement_internship_project_edit,name='Placement_internship_project_edit'),
    path('Competative_exam_edit/<id>/', request_views.Competative_exam_edit,name='Competative_exam_edit'),
    path('Sports_cultural_award_edit/<id>/', request_views.Sports_cultural_award_edit,name='Sports_cultural_award_edit'),
    path('Student_collaborative_activity_participation_edit/<id>/',request_views.Student_collaborative_activity_participation_edit,name='Student_collaborative_activity_participation_edit'),
    path('Student_bulk_upload/',request_views.Student_bulk_upload, name='Student_bulk_upload'),
]