# Generated by Django 3.2.5 on 2022-11-17 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginandregister', '0001_initial'),
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loginandregister.alluser')),
                ('enroll_num', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=15)),
                ('state_of_domicile', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=10, null=True)),
                ('year_of_admission', models.IntegerField()),
                ('nationality', models.CharField(max_length=20)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('higher_sec_school_score_card_link', models.CharField(blank=True, max_length=300, null=True)),
                ('higher_edu_inst_joined_name', models.CharField(blank=True, max_length=100, null=True)),
                ('higher_edu_prog_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institute.program')),
            ],
        ),
        migrations.CreateModel(
            name='Sports_cultural_award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('award_name', models.CharField(blank=True, max_length=50, null=True)),
                ('team_name', models.CharField(blank=True, max_length=30, null=True)),
                ('competition_type', models.CharField(blank=True, max_length=20, null=True)),
                ('event_name', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('scheme_name', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('scholarship_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('scheme_type', models.CharField(blank=True, max_length=30, null=True)),
                ('doc_link', models.CharField(blank=True, max_length=300, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Placement_internship_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('package', models.IntegerField(blank=True, null=True)),
                ('internship_project_name', models.CharField(blank=True, max_length=50, null=True)),
                ('document_link', models.CharField(blank=True, max_length=300, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Competative_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_year', models.IntegerField(blank=True, null=True)),
                ('exam_name', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('qualified_status', models.CharField(blank=True, max_length=10, null=True)),
                ('name_of_institution_joined', models.CharField(max_length=100)),
                ('program_admitted_to', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
