from django.contrib import admin
from institute.models import *
# Register your models here.
admin.site.register(Program)
admin.site.register(Collaborative_activity)
admin.site.register(Facility_dev_for_consultancy)
admin.site.register(Ict_facility)
admin.site.register(Course)
admin.site.register(Students_enrolled_in_course)
admin.site.register(Value_added_courses)
admin.site.register(Employbility_course)
admin.site.register(Category_seat_reservation)
admin.site.register(Exam_result)
admin.site.register(Program_revision)
admin.site.register(Mou)
admin.site.register(Mou_activity)
admin.site.register(Workshop_seminar)
admin.site.register(Hei_guidence_activity)
admin.site.register(Sports_cultural_event_by_intitution)
admin.site.register(E_governance)
admin.site.register(Extension_activity_award)
admin.site.register(Funds_grants_to_inst)
admin.site.register(E_library_resource)
admin.site.register(Prof_dev_skill_enhan_ext_outrch_prog)
