from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from institute import request_views
urlpatterns = [
    path('home/', request_views.displayhome),
    path('criteria_page/', request_views.display_criteria_page, name='criteria_page'),
    path('academic_home/', request_views.display_academic_home),
    path('account_home/', request_views.display_account_home),
    path('sport_home/', request_views.display_sport_home),
    path('library_home/', request_views.display_library_home),
    path('naac_cod_home/', request_views.display_naac_cod_home),
    path('admin_home/', request_views.display_admin_home),
    path('Program_delete/<id>/', request_views.Program_delete,name='Program_delete'),
    path('Collaborative_activity_delete/<id>/', request_views.Collaborative_activity_delete,name='Collaborative_activity_delete'),
    path('Facility_dev_for_consultancy_delete/<id>/', request_views.Facility_dev_for_consultancy_delete,name='Facility_dev_for_consultancy_delete'),
    path('Ict_facility_delete/<id>/', request_views.Ict_facility_delete,name='Ict_facility_delete'),
    path('Course_delete/<id>/', request_views.Course_delete, name='Course_delete'),
    path('Students_enrolled_in_course_delete/<id>/', request_views.Students_enrolled_in_course_delete, name='Students_enrolled_in_course_delete'),
    path('Value_added_courses_delete/<id>/', request_views.Value_added_courses_delete,name='Value_added_courses_delete'),
    path('Employbility_course_delete/<id>/', request_views.Employbility_course_delete,name='Employbility_course_delete'),
    path('Category_seat_reservation_delete/<id>/', request_views.Category_seat_reservation_delete,name='Category_seat_reservation_delete'),
    path('Exam_result_delete/<id>/', request_views.Exam_result_delete,name='Exam_result_delete'),
    path('Program_revision_delete/<id>/', request_views.Program_revision_delete, name='Program_revision_delete'),
    path('Mou_delete/<id>/', request_views.Mou_delete, name='Mou_delete'),
    path('Mou_activity_delete/<id>/', request_views.Mou_activity_delete, name='Mou_activity_delete'),
    path('Workshop_seminar_delete/<id>/', request_views.Workshop_seminar_delete, name='Workshop_seminar_delete'),
    path('Hei_guidence_activity_delete/<id>/', request_views.Hei_guidence_activity_delete, name='Hei_guidence_activity_delete'),
    path('Sports_cultural_event_by_intitution_delete/<id>/', request_views.Sports_cultural_event_by_intitution_delete,name='Sports_cultural_event_by_intitution_delete'),
    path('E_governance_delete/<id>/', request_views.E_governance_delete, name='E_governance_delete'),
    path('Extension_activity_award_delete/<id>/', request_views.Extension_activity_award_delete, name='Extension_activity_award_delete'),
    path('Funds_grants_to_inst_delete/<id>/', request_views.Funds_grants_to_inst_delete,name='Funds_grants_to_inst_delete'),
    path('E_library_resource_delete/<id>/', request_views.E_library_resource_delete,name='E_library_resource_delete'),
    path('Prof_dev_skill_enhan_ext_outrch_prog_delete/<id>/', request_views.Prof_dev_skill_enhan_ext_outrch_prog_delete, name='Prof_dev_skill_enhan_ext_outrch_prog_delete'),
    path('Exam_result_edit_display/<id>/',request_views.Exam_result_edit_display,name='Exam_result_edit_display'),
    path('Exam_result_edit/<id>/',request_views.Exam_result_edit,name='Exam_result_edit'),
    path('Exam_result_add_display/',request_views.Exam_result_add_display, name='Exam_result_add_display'),
    path('Exam_result_add/',request_views.Exam_result_add,name='Exam_result_add'),
    path('Facility_dev_for_consultancy_edit_display/<id>/',request_views.Facility_dev_for_consultancy_edit_display,name='Facility_dev_for_consultancy_edit_display'),
    path('Facility_dev_for_consultancy_edit/<id>/',request_views.Facility_dev_for_consultancy_edit,name='Facility_dev_for_consultancy_edit'),
    path('Facility_dev_for_consultancy_add_display/',request_views.Facility_dev_for_consultancy_add_display, name='Facility_dev_for_consultancy_add_display'),
    path('Facility_dev_for_consultancy_add/', request_views.Facility_dev_for_consultancy_add, name='Facility_dev_for_consultancy_add'),
    path('Funds_grants_to_inst_edit_display/<id>/', request_views. Funds_grants_to_inst_edit_display,name='Funds_grants_to_inst_edit_display'),
    path('Funds_grants_to_inst_edit/<id>/', request_views.Funds_grants_to_inst_edit,name='Funds_grants_to_inst_edit'),
    path('Funds_grants_to_inst_add_display/', request_views.Funds_grants_to_inst_add_display,name='Funds_grants_to_inst_add_display'),
    path('Funds_grants_to_inst_add/', request_views.Funds_grants_to_inst_add,name='Funds_grants_to_inst_add'),
    path('Sports_cultural_event_by_intitution_edit_display/<id>/', request_views.Sports_cultural_event_by_intitution_edit_display,name='Sports_cultural_event_by_intitution_edit_display'),
    path('Sports_cultural_event_by_intitution_edit/<id>/', request_views.Sports_cultural_event_by_intitution_edit, name='Sports_cultural_event_by_intitution_edit'),
    path('Sports_cultural_event_by_intitution_add_display/', request_views.Sports_cultural_event_by_intitution_add_display,name='Sports_cultural_event_by_intitution_add_display'),
    path('Sports_cultural_event_by_intitution_add/', request_views.Sports_cultural_event_by_intitution_add, name='Sports_cultural_event_by_intitution_add'),
    path('E_library_resource_edit_display/<id>/', request_views. E_library_resource_edit_display,name='E_library_resource_edit_display'),
    path('E_library_resource_edit/<id>/', request_views.E_library_resource_edit,name='E_library_resource_edit'),
    path('E_library_resource_add_display/', request_views.E_library_resource_add_display,name='E_library_resource_add_display'),
    path('E_library_resource_add/', request_views.E_library_resource_add,name='E_library_resource_add'),
]
