# Generated by Django 3.2.5 on 2022-11-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborative_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_activity', models.CharField(blank=True, max_length=50, null=True)),
                ('collaborating_agency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_collaboration', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('nature_of_activity', models.CharField(max_length=30)),
                ('document_link', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
