# Generated by Django 3.2.5 on 2022-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_collaborative_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility_dev_for_consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_developed_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_development', models.IntegerField(blank=True, null=True)),
                ('consultancy_name', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_spend', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
