# Generated by Django 3.2.5 on 2022-11-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_facility_dev_for_consultancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ict_facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=15, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=20, null=True)),
                ('link_to_geo_tagged_photos', models.CharField(blank=True, max_length=300, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.program')),
            ],
        ),
    ]
