# Generated by Django 3.2.5 on 2022-11-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_ict_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('course_name', models.CharField(blank=True, max_length=30, null=True)),
                ('year_of_intro', models.IntegerField(blank=True, null=True)),
                ('course_duration', models.IntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.program')),
            ],
        ),
        migrations.CreateModel(
            name='Value_added_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_times_offered_in_a_year', models.IntegerField(null=True)),
                ('number_of_students_completing_course', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.course')),
            ],
        ),
        migrations.CreateModel(
            name='Students_enrolled_in_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('number_of_students', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.course')),
            ],
        ),
        migrations.CreateModel(
            name='Employbility_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_performed', models.CharField(blank=True, max_length=50, null=True)),
                ('document_link', models.CharField(blank=True, max_length=300, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.course')),
            ],
        ),
    ]
