# Generated by Django 3.2.5 on 2023-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_e_governance_e_library_resource_extension_activity_award_funds_grants_to_inst_hei_guidence_activity_'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_library_resource',
            name='total_library_expenditure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
